# DO NOT MODIFY THIS FILE
# This file is auto-generated by myzsh
# Please modify custom content in $HOME/.zsh_profile

# Start configuration added by Zim install {{{
#
# User configuration sourced by login shells
#

# Initialize Zim
source ${ZIM_HOME}/login_init.zsh -q &!
# }}} End configuration added by Zim install

# DO NOT MODIFY THIS FILE
# This file is auto-generated by myzsh
# Please modify custom content in $HOME/.zsh_profile
